#! /bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10G
#
#SBATCH --partition mctavish.q
#SBATCH --time=0-02:1000:00     # 2 days 1000 minutes
#
  #SBATCH --output=USERNAME-TAXONNAME-YEAR-MONTH-DAY.stdout
#SBATCH --error=USERNAME-TAXONNAME-YEAR-MONTH-DAY.stderr
#

#SBATCH --export=ALL

pwd
## Add dependcies to PATH
export PATH=/branchinecta/shared/bin:$PATH
## Activate virtual env (we are not using conda no more)
source /branchinecta/shared/venv-physcraper/bin/activate
## Move to folder containing inputs (or where you want to save outputs)
cd /branchinecta/shared/
pwd
echo "Starting Physcraper TAXONNAME run"
time physcraper_run.py --study_id STUDY_ID --tree_id TREE_ID --treebase -db ./local_blast_db_OLD/ --search_taxon ott:OTT_ID_NUMBER -o ./collab-paper/linked_dir/USERNAME-TAXONNAME-YEAR-MONTH-DAY
