#! /bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=10G
#
#SBATCH --partition mctavish.q
#SBATCH --time=0-10:200:00     # 2days 0 minutes
#
#SBATCH --output=physcraper_local_%j.stdout
#SBATCH --error=physcraper_local_%j.stderr
#

#SBATCH --export=ALL

# This submission file will run a simple set of commands. All stdout will be
# captured in mmyjob_XXXX.stdout (as specified in the Slurm command above).
# This job file uses a shared-memory parallel environment and requests 1 cores
# on a single node.This script loads PGI compiler module named "pgi"

export PATH=/branchinecta/shared/bin:$PATH
source /branchinecta/shared/venv-physcraper/bin/activate
cd /branchinecta/shared

physcraper_run.py -tf tests/data/tiny_test_example/test.tre -tfs newick -a tests/data/tiny_test_example/test.fas --taxon_info tests/data/tiny_test_example/main.json -as fasta -db /branchinecta/shared/local_blast_db_OLD/ -o luna_test
